name: BEYBLADE Charts & Updates

on:
  workflow_dispatch:

jobs:
  generate-plots:
    name: Generate Plots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate plots
        run: |
          python ./scripts/gen_plots.py --mode official
          python ./scripts/gen_plots.py --mode private

      - name: Upload plots as artifact
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: |
            ./data/plots
            ./plots/private

  run-update-script:
    name: Run Update Script
    runs-on: ubuntu-latest
    #needs: generate-plots   # optional, falls Update nach Plots laufen soll
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Sheets credentials
        run: |
            echo "${{ secrets.GSHEETS_CREDENTIALS_JSON }}" > service_account.json
            export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json

      - name: Run update script
        run: |
          python update.py -d
